name: dart_multimethod
description: dart_multimethod is a library for implementing multimethods in Dart.
version: 0.0.2
homepage: https://github.com/CAPHTECH/dart_multimethod

environment:
  sdk: '>=3.1.0 <4.0.0'

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.24.9
